export const record = [
  {
    image: require("./assets/sachin.jpg"),
    id: "1",
    "account ": "Sachin",
    "followers ": 2000,
    following: 200,
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    image: require("./assets/triangle.png"),
    id: "2",
    "account ": "Deepak",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "3",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "3",
    image: require("./assets/triangle.png"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "4",
    image: require("./assets/triangle.png"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "5",
    image: require("./assets/triangle.png"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "6",
    image: require("./assets/triangle.png"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "7",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "8",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "9",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "10",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "11",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "12",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "13",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "14",
    image: require("./assets/triangle.png"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "15",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "16",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "17",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "18",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "19",
    image: require("./assets/triangle.png"),

    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "20",
    image: require("./assets/sachin.jpg"),
    "account ": "Rahman",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "21",
    image: require("./assets/triangle.png"),

    "account ": "Yash",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
  {
    id: "22",
    image: require("./assets/sachin.jpg"),
    "account ": "Vinay",
    "followers ": 2000,
    following: "200",
    tags: "cricket",
    "action ": " Delete ",
  },
];
